// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7bUH2cVmKciWg-pN5yOh8Iv2J9CyrHvU',
    appId: '1:936648392999:web:cf1cf3ee1447e21db6a902',
    messagingSenderId: '936648392999',
    projectId: 'kryssna-16904',
    authDomain: 'kryssna-16904.firebaseapp.com',
    databaseURL: 'https://kryssna-16904-default-rtdb.firebaseio.com',
    storageBucket: 'kryssna-16904.appspot.com',
    measurementId: 'G-P47RSCZYG9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDwcP9CtB57JR4nZAfBB1F2bLjUNYA6gI',
    appId: '1:936648392999:android:bf1cef1766149766b6a902',
    messagingSenderId: '936648392999',
    projectId: 'kryssna-16904',
    databaseURL: 'https://kryssna-16904-default-rtdb.firebaseio.com',
    storageBucket: 'kryssna-16904.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxoJnSRizoc7A-9HxCShsQdcBv8HDmX50',
    appId: '1:936648392999:ios:4f793fd72f8f1d50b6a902',
    messagingSenderId: '936648392999',
    projectId: 'kryssna-16904',
    databaseURL: 'https://kryssna-16904-default-rtdb.firebaseio.com',
    storageBucket: 'kryssna-16904.appspot.com',
    iosClientId: '936648392999-v741m6t3tl7hgo4b6s4tdvr7sf7r3rck.apps.googleusercontent.com',
    iosBundleId: 'com.example.kryssna',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxoJnSRizoc7A-9HxCShsQdcBv8HDmX50',
    appId: '1:936648392999:ios:345d6fe18f64cc86b6a902',
    messagingSenderId: '936648392999',
    projectId: 'kryssna-16904',
    databaseURL: 'https://kryssna-16904-default-rtdb.firebaseio.com',
    storageBucket: 'kryssna-16904.appspot.com',
    iosClientId: '936648392999-8u576dj8mcp0h8eobkei4abt08h958p5.apps.googleusercontent.com',
    iosBundleId: 'com.example.kryssna.RunnerTests',
  );
}
