name: Dart CI

on:
  [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Setup Dart SDK
        run: |
          curl https://storage.googleapis.com/dart-archive/channels/stable/release/latest/sdk/dartsdk-windows-x64-release.zip -o dartsdk.zip
          tar -xf dartsdk.zip
          echo 'export PATH="$PATH:$PWD/dart-sdk/bin"' >> $PROFILE
          refreshenv

      - name: Setup Flutter SDK
        run: |
          curl https://storage.googleapis.com/flutter_infra/releases/stable/windows/flutter_windows_2.8.0-stable.zip -o flutter.zip
          tar -xf flutter.zip
          echo 'export PATH="$PATH:$PWD/flutter/bin"' >> $PROFILE
          refreshenv

      - uses: actions/checkout@v1

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test

      - name: Run analyzer
        run: flutter analyze
        if: always()

      - name: Run dartfmt
        run: flutter format --dry-run --set-exit-if-changed .
        if: always()
