name: Dart CI

on:
  [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - name: Setup Dart SDK
        run: |
          if [ "${{ matrix.os }}" == "macos-latest" ]; then
            brew tap dart-lang/dart
            brew install dart
          else
            choco install dart-sdk
          fi

      - name: Setup Flutter SDK
        run: |
          if [ "${{ matrix.os }}" == "macos-latest" ]; then
            brew update
            brew install --cask flutter
          else
            choco install flutter
          fi

      - uses: actions/checkout@v1

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test

      - name: Run analyzer
        run: flutter analyze
        if: always()

      - name: Run dartfmt
        run: flutter format --dry-run --set-exit-if-changed .
        if: always()
